force-app/main/default/objects/SA_Restricted_Word__c/SA_Restricted_Word__c.object-meta.xml
<CustomObject>
    <label>SA Restricted Word</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>SA Restricted Word Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Restricted Words</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Restricted_Word__c/fields/Designation_Type__c.field-meta.xml
<CustomField>
    <fullName>Designation_Type__c</fullName>
    <label>Designation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foul Language</fullName>
            </value>
            <value>
                <fullName>Confidential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word__c/fields/Override_Substitution__c.field-meta.xml
<CustomField>
    <fullName>Override_Substitution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Substitution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word__c/fields/RegexValue__c.field-meta.xml
<CustomField>
    <fullName>RegexValue__c</fullName>
    <label>RegexValue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word__c/fields/ReplacementRegexValue__c.field-meta.xml
<CustomField>
    <fullName>ReplacementRegexValue__c</fullName>
    <label>ReplacementRegexValue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word__c/fields/Substitution__c.field-meta.xml
<CustomField>
    <fullName>Substitution__c</fullName>
    <label>Substitution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word__c/fields/Word__c.field-meta.xml
<CustomField>
    <fullName>Word__c</fullName>
    <label>Word</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/SA_Restricted_Word_Audit__c.object-meta.xml
<CustomObject>
    <label>SA Restricted Word Audit</label>
    <nameField>
        <displayFormat>RWA-{0000}</displayFormat>
        <label>SA Restricted Word Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Restricted Word Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/fields/Breached_By__c.field-meta.xml
<CustomField>
    <fullName>Breached_By__c</fullName>
    <label>Breached By</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/fields/Designation_Type__c.field-meta.xml
<CustomField>
    <fullName>Designation_Type__c</fullName>
    <label>Designation Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/fields/Masked_Text__c.field-meta.xml
<CustomField>
    <fullName>Masked_Text__c</fullName>
    <label>Masked Text</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/fields/Matching_Restricted_Word__c.field-meta.xml
<CustomField>
    <fullName>Matching_Restricted_Word__c</fullName>
    <label>Matching Restricted Word</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SA_Restricted_Word_Audit__c/fields/Unmasked_Text__c.field-meta.xml
<CustomField>
    <fullName>Unmasked_Text__c</fullName>
    <label>Unmasked Text</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SArwaUtilityCls.cls
public without sharing class SArwaUtilityCls {
    @AuraEnabled
    public static String rwlCheckAudit(String prompt) {
        System.debug('#### input prompt: ' + prompt);
        String auditReqString = prompt;
        String auditRespString = '';
        auditRespString = SArwaCustomModelAPI.createGeneration(auditReqString);
        
        String auditedReqString = auditReqString;
        String auditedRespString = auditRespString;
        Map<String, String> retMap = new Map<String, String>();
        List<SA_Restricted_Word_Audit__c> newRwaList = new List<SA_Restricted_Word_Audit__c>();
        Map<Id, SA_Restricted_Word__c> rwMap = new Map<Id, SA_Restricted_Word__c>();
        rwMap = new Map<Id, SA_Restricted_Word__c>([SELECT Id, Name, Word__c, RegexValue__c, ReplacementRegexValue__c, Substitution__c, Designation_Type__c, Override_Substitution__c
         											FROM SA_Restricted_Word__c
         											WHERE isActive__c = :true]);
        SA_Restricted_Word_Audit__c newRwa = null;
        Matcher mtr;
        Pattern ptr;
        for(Id eachId : rwmap.keySet()){
            ptr = Pattern.compile(rwMap.get(eachId).RegexValue__c);
            mtr = ptr.Matcher(auditedReqString);
            if(mtr.find()){
                auditedReqString = auditedReqString.replaceAll(rwMap.get(eachId).RegexValue__c, rwMap.get(eachId).Substitution__c);
                newRwa = new SA_Restricted_Word_Audit__c(Breached_By__c=System.UserInfo.getName(), Unmasked_Text__c=auditReqString, Designation_Type__c=rwMap.get(eachId).Designation_Type__c,
                                                        Masked_Text__c=auditedReqString, Matching_Restricted_Word__c=rwMap.get(eachId).Word__c);
                newRwaList.add(newRwa);
            }
            mtr = ptr.Matcher(auditedRespString);
            if(mtr.find()){
                auditedRespString = auditedRespString.replaceAll(rwMap.get(eachId).RegexValue__c, rwMap.get(eachId).Substitution__c);
                newRwa = new SA_Restricted_Word_Audit__c(Breached_By__c='Agentforce Agent', Unmasked_Text__c=auditRespString, Designation_Type__c=rwMap.get(eachId).Designation_Type__c,
                                                        Masked_Text__c=auditedRespString, Matching_Restricted_Word__c=rwMap.get(eachId).Word__c);
                newRwaList.add(newRwa);
            }
        }
        if(!newRwaList.isEmpty()){
            try{
                System.debug('#### size of list: ' + newRwaList.size());
                Database.SaveResult[] saveList = Database.insert(newRwaList);
            }catch(DmlException e){
                System.debug('#### Exception occured while inserting restricted word audit records' + e.getMessage());
            }catch(Exception e){
                System.debug('#### An unexpected error has occured: ' + e.getMessage());
            }
        }
        System.debug('#### Req String: ' + auditReqString + ' ReqAudit String: ' + auditedReqString);
        System.debug('#### Resp String: ' + auditRespString + ' RespAudit String: ' + auditedRespString);
        retMap.put('auditedReqString', auditedReqString);
        retMap.put('auditedRespString', auditedRespString);
        return auditedRespString;
    }
}